solon.app.name=simbot-solon-onebot11-napcat-demo-java

simbot.enabled=true
simbot.components.autoInstallProviders=true
simbot.components.autoInstallProviderConfigures=true
simbot.plugins.autoInstallProviders=true
simbot.plugins.autoInstallProviderConfigures=true
simbot.bots.autoStartBots=true
simbot.bots.autoStartMode=ASYNC
simbot.bots.configurationJsonResources[0]=file:./simbot-bots/*.bot.json
simbot.bots.autoRegistrationResourceLoadFailurePolicy=ERROR
simbot.bots.autoRegistrationFailurePolicy=ERROR
simbot.bots.autoRegistrationMismatchConfigurableBotManagerPolicy=ERROR_LOG
